FROM nginx:latest
COPY diag_circ.html /usr/share/nginx/html/diag_circ.html
COPY diag_ope.html /usr/share/nginx/html/diag_ope.html
COPY histo.html /usr/share/nginx/html/histo.html
COPY map.html /usr/share/nginx/html/map.html
EXPOSE 80