apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: service
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
